### ISSUE TITLE
Uncaught Error: EPERM: operation not permitted, scandir 'C:\Users\bob.buford\AppData\Local\Applic...

### ISSUE THREAD

**Issue by BobBuford** [benjaminRomano/gulp-manager#4]
[Enter steps to reproduce below:]
1. ...installed Atom using Chocolatey
2. ...ran atom > install shell commands
3. ...files shell and command created - both empty
4. ...closing, then launching Atom - it opens with no menu bar, and with this error.

**Atom Version**: 1.0.19
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [gulp-manager](https://github.com/benjaminRomano/gulp-manager) package, v0.2.12
### Stack Trace

Uncaught Error: EPERM: operation not permitted, scandir 'C:\Users\bob.buford\AppData\Local\Application Data'

```
At fs.js:813

Error: EPERM: operation not permitted, scandir 'C:\Users\bob.buford\AppData\Local\Application Data'
  at Error (native)
  at Object.fs.readdirSync (fs.js:813:18)
  at Object.fs.readdirSync (ATOM_SHELL_ASAR.js:449:28)
  at findFilesHelper (C:\Users\bob.buford\.atom\packages\gulp-manager\lib\file-finder-util.coffee:33:5)
  at findFilesHelper (C:\Users\bob.buford\.atom\packages\gulp-manager\lib\file-finder-util.coffee:44:23)
  at findFilesHelper (C:\Users\bob.buford\.atom\packages\gulp-manager\lib\file-finder-util.coffee:44:23)
  at findFilesHelper (C:\Users\bob.buford\.atom\packages\gulp-manager\lib\file-finder-util.coffee:44:23)
  at C:\Users\bob.buford\.atom\packages\gulp-manager\lib\file-finder-util.coffee:24:21
  at Array.map (native)
  at FileFinderUtil.findFiles (C:\Users\bob.buford\.atom\packages\gulp-manager\lib\file-finder-util.coffee:24:7)
  at GulpPaneView.getGulpfiles (C:\Users\bob.buford\.atom\packages\gulp-manager\lib\views\gulp-pane.coffee:35:5)
  at GulpPaneView.initialize (C:\Users\bob.buford\.atom\packages\gulp-manager\lib\views\gulp-pane.coffee:30:6)
  at GulpPaneView.View (C:\Users\bob.buford\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:184:25)
  at GulpPaneView.DockPaneView (C:\Users\bob.buford\.atom\packages\grunt-manager\node_modules\atom-bottom-dock\lib\dock-pane-view.coffee:4:3)
  at new GulpPaneView (C:\Users\bob.buford\.atom\packages\gulp-manager\lib\views\gulp-pane.coffee:9:3)
  at Object.module.exports.add (C:\Users\bob.buford\.atom\packages\gulp-manager\lib\main.coffee:28:21)
  at Object.module.exports.consumeBottomDock (C:\Users\bob.buford\.atom\packages\gulp-manager\lib\main.coffee:24:6)
  at Provider.module.exports.Provider.provide (C:\Users\bob.buford\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\service-hub\lib\provider.js:30:52)
  at C:\Users\bob.buford\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\service-hub\lib\service-hub.js:55:26
  at doNTCallback0 (node.js:416:9)
  at process._tickCallback (node.js:345:13)

```
### Commands

```
  2x -0:05.0 blur (atom-text-editor.editor.is-focused.vim-mode-plus.normal-mode)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "solarized-light-syntax"
    ],
    "autoHideMenuBar": true
  }
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.3.3
api-docs, v0.0.3
asciidoc-preview, v0.6.0
atom-alignment, v0.12.1
atom-bootstrap4, v1.2.13
atom-jshint, v2.0.0
atom-math, v0.0.3
atom-minify, v0.4.2
atom-shortcuts, v0.0.2
atom-special-char-highlighter, v0.1.0
atometer, v0.1.0
bottom-dock, v0.3.5
build-tools-change-project, v0.1.0
case-switch, v0.5.0
change-case, v0.6.0
clipboard-plus, v0.5.1
coffee-refactor, v0.7.0
docblockr, v0.7.3
dockerletion, v0.1.0
emmet, v2.3.13
emmet-simplified, v2.5.0
emmet-snippets-compatibility, v1.0.0
git-log, v0.4.1
github-utils, v0.7.0
grunt-manager, v0.1.10
gulp-manager, v0.2.12
js-patterns-atom-snippets, v0.2.1
js-refactor, v0.6.0
language-docker, v1.1.3
language-js-specs, v0.1.0
new-file-plus, v0.2.1
project-manager, v2.6.5
project-view, v0.1.2
project-viewer, v0.2.1
refactor, v0.6.0
remote-edit, v1.8.21
Remote-FTP, v0.7.8
terminal-plus, v0.11.2
todo-manager, v0.2.5
tree-view-filter, v0.3.7
tree-view-git-branch, v0.0.6
tree-view-git-status, v0.2.2
tree-view-open-files, v0.2.4
underline-trailing-whitespace, v1.4.0
vim-mode-clipboard-plus, v0.1.0
vim-mode-plus, v0.1.6

# Dev
No dev packages
```

**Comment by benjaminRomano** [comment]
I just pushed out an update that should fix this for you.
