### ISSUE TITLE
Failed to load the gulp-manager package

### ISSUE THREAD

**Issue by dotcollective-brendon** [benjaminRomano/gulp-manager#9]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.4.0
**System**: Mac OS X 10.10.5
**Thrown From**: [gulp-manager](https://github.com/benjaminRomano/gulp-manager) package, v0.2.18
### Stack Trace

Failed to load the gulp-manager package

```
At Cannot find module 'underscore-plus'

Error: Cannot find module 'underscore-plus'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/elitepsdcoding/.atom/packages/gulp-manager/node_modules/space-pen/lib/space-pen.js:8:9)
    at Object.<anonymous> (/Users/elitepsdcoding/.atom/packages/gulp-manager/node_modules/space-pen/lib/space-pen.js:634:4)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/elitepsdcoding/.atom/packages/gulp-manager/node_modules/atom-bottom-dock/lib/dock-pane-view.coffee:1:10)
    at Object.<anonymous> (/Users/elitepsdcoding/.atom/packages/gulp-manager/node_modules/atom-bottom-dock/lib/dock-pane-view.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/elitepsdcoding/.atom/packages/gulp-manager/node_modules/atom-bottom-dock/lib/main.coffee:1:24)
    at Object.<anonymous> (/Users/elitepsdcoding/.atom/packages/gulp-manager/node_modules/atom-bottom-dock/lib/main.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/elitepsdcoding/.atom/packages/gulp-manager/lib/main.coffee:2:20)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "snippets"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.7.15
autoclose-html, v0.19.0
bottom-dock, v0.3.7
gulp-manager, v0.2.18
remote-sync, v3.5.0
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by benjaminRomano** [comment]
Try doing `npm install` in .atom/packages/gulp-manager or re-installing the package.

**Comment by dotcollective-brendon** [comment]
@benjaminRomano Thanks, npm install worked
